In [12]:
import pandas as pd
import numpy as np
import datetime as dt

In [4]:
ubna_file_records = pd.read_csv('../output_dir/ubna_data_04_collected_audio_records.csv', index_col=0)
ubna_file_records

,datetime_UTC,site_name,recover_folder,audiomoth_num,sd_card_num,file_path,file_metadata,file_status,audiomoth_temperature,audiomoth_battery,sample_rate,audiomoth_artist_ID,file_duration,Deployment notes
0,2024-05-10 21:10:00,E18 Bridge,recover-20240517,G,1,/mnt/ubna_data_04/recover-20240517/UBNA_001/20...,Recorded at 21:10:00 10/05/2024 (UTC) by Audio...,Usable for detection,22.8C,4.1V,192000,AudioMoth 245AAA0563FACFB3,300.001270833333,Ikea Batteries 0:00-24:00 UTC; Configured to 5...
1,2024-05-10 21:20:00,E18 Bridge,recover-20240517,G,1,/mnt/ubna_data_04/recover-20240517/UBNA_001/20...,Recorded at 21:20:00 10/05/2024 (UTC) by Audio...,Usable for detection,23.3C,4.1V,192000,AudioMoth 245AAA0563FACFB3,300.001270833333,Ikea Batteries 0:00-24:00 UTC; Configured to 5...
2,2024-05-10 21:30:00,E18 Bridge,recover-20240517,G,1,/mnt/ubna_data_04/recover-20240517/UBNA_001/20...,Recorded at 21:30:00 10/05/2024 (UTC) by Audio...,Usable for detection,23.7C,4.1V,192000,AudioMoth 245AAA0563FACFB3,300.001270833333,Ikea Batteries 0:00-24:00 UTC; Configured to 5...
3,2024-05-10 21:40:00,E18 Bridge,recover-20240517,G,1,/mnt/ubna_data_04/recover-20240517/UBNA_001/20...,Recorded at 21:40:00 10/05/2024 (UTC) by Audio...,Usable for detection,24.7C,4.0V,192000,AudioMoth 245AAA0563FACFB3,300.001270833333,Ikea Batteries 0:00-24:00 UTC; Configured to 5...
4,2024-05-10 21:49:11,E18 Bridge,recover-20240517,G,1,/mnt/ubna_data_04/recover-20240517/UBNA_001/20...,Recorded at 21:49:11 10/05/2024 (UTC) by Audio...,Usable for detection,27.4C,4.0V,192000,AudioMoth 245AAA0563FACFB3,0.00127083333333333,Ikea Batteries 0:00-24:00 UTC; Configured to 5...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
177708,2025-01-27 18:20:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 18:20:00 27/01/2025 (UTC) by Audio...,Usable for detection,7.1C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
177709,2025-01-27 18:30:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 18:30:00 27/01/2025 (UTC) by Audio...,Usable for detection,7.1C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
177710,2025-01-27 18:40:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 18:40:00 27/01/2025 (UTC) by Audio...,Usable for detection,7.2C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
177711,2025-01-27 18:50:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 18:50:00 27/01/2025 (UTC) by Audio...,Usable for detection,8.3C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
177712,2025-01-27 19:00:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 19:00:00 27/01/2025 (UTC) by Audio...,Usable for detection,7.7C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...

In [14]:
ubna_file_records[pd.to_datetime(ubna_file_records['datetime_UTC'])>=dt.datetime(2024,11,6)].reset_index(drop=True)

,datetime_UTC,site_name,recover_folder,audiomoth_num,sd_card_num,file_path,file_metadata,file_status,audiomoth_temperature,audiomoth_battery,sample_rate,audiomoth_artist_ID,file_duration,Deployment notes
0,2024-11-06 00:00:00,Foliage,recover-20241118,B,27,/mnt/ubna_data_04/recover-20241118/UBNA_027/20...,Recorded at 00:00:00 06/11/2024 (UTC) by Audio...,Usable for detection,6.1C,4.1V,192000,AudioMoth 24F3190863FA4B5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
1,2024-11-06 00:10:00,Foliage,recover-20241118,B,27,/mnt/ubna_data_04/recover-20241118/UBNA_027/20...,Recorded at 00:10:00 06/11/2024 (UTC) by Audio...,Usable for detection,5.6C,4.1V,192000,AudioMoth 24F3190863FA4B5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
2,2024-11-06 00:20:00,Foliage,recover-20241118,B,27,/mnt/ubna_data_04/recover-20241118/UBNA_027/20...,Recorded at 00:20:00 06/11/2024 (UTC) by Audio...,Usable for detection,5.3C,4.1V,192000,AudioMoth 24F3190863FA4B5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
3,2024-11-06 00:30:00,Foliage,recover-20241118,B,27,/mnt/ubna_data_04/recover-20241118/UBNA_027/20...,Recorded at 00:30:00 06/11/2024 (UTC) by Audio...,Usable for detection,5.3C,4.1V,192000,AudioMoth 24F3190863FA4B5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
4,2024-11-06 00:40:00,Foliage,recover-20241118,B,27,/mnt/ubna_data_04/recover-20241118/UBNA_027/20...,Recorded at 00:40:00 06/11/2024 (UTC) by Audio...,Usable for detection,5.0C,4.1V,192000,AudioMoth 24F3190863FA4B5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46955,2025-01-27 18:20:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 18:20:00 27/01/2025 (UTC) by Audio...,Usable for detection,7.1C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
46956,2025-01-27 18:30:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 18:30:00 27/01/2025 (UTC) by Audio...,Usable for detection,7.1C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
46957,2025-01-27 18:40:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 18:40:00 27/01/2025 (UTC) by Audio...,Usable for detection,7.2C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
46958,2025-01-27 18:50:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 18:50:00 27/01/2025 (UTC) by Audio...,Usable for detection,8.3C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
46959,2025-01-27 19:00:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 19:00:00 27/01/2025 (UTC) by Audio...,Usable for detection,7.7C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...

In [17]:
last_deployment = ubna_file_records[ubna_file_records['recover_folder']=='recover-20250127'].reset_index(drop=True)
last_deployment

,datetime_UTC,site_name,recover_folder,audiomoth_num,sd_card_num,file_path,file_metadata,file_status,audiomoth_temperature,audiomoth_battery,sample_rate,audiomoth_artist_ID,file_duration,Deployment notes
0,2025-01-13 17:42:47,Telephone Field,recover-20250127,L,22,/mnt/ubna_data_04/recover-20250127/UBNA_022/20...,Recorded at 17:42:47 13/01/2025 (UTC) by Audio...,Usable for detection,22.9C,4.1V,192000,AudioMoth 242A260463FACFE7,133.001940104167,Ikea Batteries 0:00-24:00 UTC; All new batteri...
1,2025-01-13 18:00:00,Telephone Field,recover-20250127,L,22,/mnt/ubna_data_04/recover-20250127/UBNA_022/20...,Recorded at 18:00:00 13/01/2025 (UTC) by Audio...,Usable for detection,23.3C,4.1V,192000,AudioMoth 242A260463FACFE7,300.001940104167,Ikea Batteries 0:00-24:00 UTC; All new batteri...
2,2025-01-13 18:10:00,Telephone Field,recover-20250127,L,22,/mnt/ubna_data_04/recover-20250127/UBNA_022/20...,Recorded at 18:10:00 13/01/2025 (UTC) by Audio...,Usable for detection,22.5C,4.1V,192000,AudioMoth 242A260463FACFE7,300.001940104167,Ikea Batteries 0:00-24:00 UTC; All new batteri...
3,2025-01-13 18:20:00,Telephone Field,recover-20250127,L,22,/mnt/ubna_data_04/recover-20250127/UBNA_022/20...,Recorded at 18:20:00 13/01/2025 (UTC) by Audio...,Usable for detection,19.3C,4.1V,192000,AudioMoth 242A260463FACFE7,300.001940104167,Ikea Batteries 0:00-24:00 UTC; All new batteri...
4,2025-01-13 18:30:00,Telephone Field,recover-20250127,L,22,/mnt/ubna_data_04/recover-20250127/UBNA_022/20...,Recorded at 18:30:00 13/01/2025 (UTC) by Audio...,Usable for detection,17.1C,4.1V,192000,AudioMoth 242A260463FACFE7,300.001940104167,Ikea Batteries 0:00-24:00 UTC; All new batteri...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5626,2025-01-27 18:20:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 18:20:00 27/01/2025 (UTC) by Audio...,Usable for detection,7.1C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
5627,2025-01-27 18:30:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 18:30:00 27/01/2025 (UTC) by Audio...,Usable for detection,7.1C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
5628,2025-01-27 18:40:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 18:40:00 27/01/2025 (UTC) by Audio...,Usable for detection,7.2C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
5629,2025-01-27 18:50:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 18:50:00 27/01/2025 (UTC) by Audio...,Usable for detection,8.3C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...
5630,2025-01-27 19:00:00,Carp Pond,recover-20250127,C,25,/mnt/ubna_data_04/recover-20250127/UBNA_025/20...,Recorded at 19:00:00 27/01/2025 (UTC) by Audio...,Usable for detection,7.7C,3.7V,192000,AudioMoth 24F319055FDF2F5B,300.001270833333,Ikea Batteries 0:00-24:00 UTC; All new batteri...

In [18]:
last_deployment.to_csv('20250225__recover-20250127_collected_audio_records.csv')

In [8]:
bd2_file_df = pd.read_csv('20250130__group_threshold_sweep_results/bd2__threshold0p00_chunksize2_20220826_070000_REDUCED_OVERLAPS.csv', index_col=0)
selected_bd2_file_df = bd2_file_df[(bd2_file_df['det_prob']>=0.35)&(bd2_file_df['SNR']>=3)]
selected_bd2_file_df

,freq_group,peak_frequency_time_SPECTROGRAM,peak_frequency_SPECTROGRAM,peak_frequency_WELCH,SNR,start_time,end_time,low_freq,high_freq,class,class_prob,det_prob,individual,event,sampling_rate,input_file
63,HF,1.732025,48000.0,47040.0,3.570422,1.7295,1.7371,46953,51351,Pipistrellus pipistrellus,0.388,0.428,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...
154,HF,3.773588,48000.0,46080.0,6.879404,3.7705,3.7771,45234,54096,Pipistrellus pipistrellus,0.466,0.512,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...
164,HF,3.914558,48000.0,46080.0,8.649871,3.9105,3.9154,45234,59565,Pipistrellus pipistrellus,0.266,0.355,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...
189,HF,4.310792,48000.0,47040.0,10.101822,4.3085,4.3140,46093,59238,Pipistrellus pipistrellus,0.512,0.542,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...
196,HF,4.445529,48000.0,47040.0,11.660364,4.4425,4.4477,44375,59482,Pipistrellus pipistrellus,0.363,0.470,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91137,HF,1787.780496,42000.0,39360.0,9.656562,1787.7745,1787.7849,37500,46675,Pipistrellus nathusii,0.492,0.587,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...
91142,HF,1787.962204,42000.0,40320.0,6.562988,1787.9595,1787.9694,37500,45913,Pipistrellus nathusii,0.537,0.591,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...
91155,HF,1788.217425,42000.0,41280.0,8.990165,1788.2125,1788.2212,39218,48186,Pipistrellus nathusii,0.431,0.544,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...
91165,HF,1788.419000,42000.0,41280.0,5.583953,1788.4135,1788.4225,40078,49982,Pipistrellus nathusii,0.441,0.566,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...
91170,HF,1788.500058,42000.0,40320.0,4.144408,1788.4955,1788.5034,38359,47881,Pipistrellus nathusii,0.419,0.560,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...

In [13]:
def convert_bd2df_ravenpro(df: pd.DataFrame):
    """
    Converts a dataframe to the format used by RavenPro
    """

    ravenpro_df = df.copy()

    ravenpro_df.rename(columns={
        "start_time": "Begin Time (s)",
        "end_time": "End Time (s)",
        "low_freq": "Low Freq (Hz)",
        "high_freq": "High Freq (Hz)",
        "event": "Annotation",
        "freq_group":"Manually-Verified Phonic Group",
        'snr_nist_quick_dB':'SNR NIST Quick (dB)',
        'delta_time_s':'Delta Time (s)'
    }, inplace=True)

    ravenpro_df["Selection"] = np.arange(0, df.shape[0]).astype('int') + 1
    ravenpro_df["View"] = "Waveform 1"
    ravenpro_df["Channel"] = "1"

    return ravenpro_df

In [14]:
selected_bd2_file_txt = convert_bd2df_ravenpro(selected_bd2_file_df)
selected_bd2_file_txt

,Manually-Verified Phonic Group,peak_frequency_time_SPECTROGRAM,peak_frequency_SPECTROGRAM,peak_frequency_WELCH,SNR,Begin Time (s),End Time (s),Low Freq (Hz),High Freq (Hz),class,class_prob,det_prob,individual,Annotation,sampling_rate,input_file,Selection,View,Channel
63,HF,1.732025,48000.0,47040.0,3.570422,1.7295,1.7371,46953,51351,Pipistrellus pipistrellus,0.388,0.428,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...,1,Waveform 1,1
154,HF,3.773588,48000.0,46080.0,6.879404,3.7705,3.7771,45234,54096,Pipistrellus pipistrellus,0.466,0.512,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...,2,Waveform 1,1
164,HF,3.914558,48000.0,46080.0,8.649871,3.9105,3.9154,45234,59565,Pipistrellus pipistrellus,0.266,0.355,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...,3,Waveform 1,1
189,HF,4.310792,48000.0,47040.0,10.101822,4.3085,4.3140,46093,59238,Pipistrellus pipistrellus,0.512,0.542,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...,4,Waveform 1,1
196,HF,4.445529,48000.0,47040.0,11.660364,4.4425,4.4477,44375,59482,Pipistrellus pipistrellus,0.363,0.470,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...,5,Waveform 1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
91137,HF,1787.780496,42000.0,39360.0,9.656562,1787.7745,1787.7849,37500,46675,Pipistrellus nathusii,0.492,0.587,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...,2719,Waveform 1,1
91142,HF,1787.962204,42000.0,40320.0,6.562988,1787.9595,1787.9694,37500,45913,Pipistrellus nathusii,0.537,0.591,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...,2720,Waveform 1,1
91155,HF,1788.217425,42000.0,41280.0,8.990165,1788.2125,1788.2212,39218,48186,Pipistrellus nathusii,0.431,0.544,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...,2721,Waveform 1,1
91165,HF,1788.419000,42000.0,41280.0,5.583953,1788.4135,1788.4225,40078,49982,Pipistrellus nathusii,0.441,0.566,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...,2722,Waveform 1,1
91170,HF,1788.500058,42000.0,40320.0,4.144408,1788.4955,1788.5034,38359,47881,Pipistrellus nathusii,0.419,0.560,-1,Echolocation,192000,/Users/adityakrishna/Documents/Research/mila_f...,2723,Waveform 1,1

In [15]:
selected_bd2_file_txt.to_csv('/Users/adityakrishna/Downloads/selected_20220826_070000.txt', sep='\t')