In [30]:
import pandas as pd
import dask.dataframe as dd
import datetime as dt

from pathlib import Path

import numpy as np

In [22]:
ubna_data_01_df = pd.read_csv('../output_dir/ubna_data_01_collected_audio_records.csv', index_col=0)
dc_season1 = ubna_data_01_df[pd.to_datetime(ubna_data_01_df['Datetime UTC'])>=dt.datetime(2022,1,1)]
dc_season1.head(5)

,Datetime UTC,Site name,Recover folder,AudioMoth #,SD card #,File path,File metadata,File status,Audiomoth temperature,Audiomoth battery,Sample rate,Audiomoth artist ID,File duration,Deployment notes
1233,2022-06-14 22:36:27,Foliage,recover-20220616_unit2,C,010,/mnt/ubna_data_01/recover-20220616_unit2/20220...,Recorded at 22:36:27 14/06/2022 (UTC) by Audio...,Usable for detection,27.5C,4.7V,250000,AudioMoth 24F319055FDF2F5B,1408,Weather has been partly cloudy with occasional...
1234,2022-06-14 23:00:00,Foliage,recover-20220616_unit2,C,010,/mnt/ubna_data_01/recover-20220616_unit2/20220...,Recorded at 23:00:00 14/06/2022 (UTC) by Audio...,Usable for detection,18.8C,4.7V,250000,AudioMoth 24F319055FDF2F5B,1795,Weather has been partly cloudy with occasional...
1235,2022-06-14 23:30:00,Foliage,recover-20220616_unit2,C,010,/mnt/ubna_data_01/recover-20220616_unit2/20220...,Recorded at 23:30:00 14/06/2022 (UTC) by Audio...,Usable for detection,17.7C,4.6V,250000,AudioMoth 24F319055FDF2F5B,1795,Weather has been partly cloudy with occasional...
1236,2022-06-15 00:00:00,Foliage,recover-20220616_unit2,C,010,/mnt/ubna_data_01/recover-20220616_unit2/20220...,Recorded at 00:00:00 15/06/2022 (UTC) by Audio...,Usable for detection,16.7C,4.6V,250000,AudioMoth 24F319055FDF2F5B,421,Weather has been partly cloudy with occasional...
1237,2022-06-15 00:30:00,Foliage,recover-20220616_unit2,C,010,/mnt/ubna_data_01/recover-20220616_unit2/20220...,Recorded at 00:30:00 15/06/2022 (UTC) by Audio...,Usable for detection,16.0C,4.5V,250000,AudioMoth 24F319055FDF2F5B,1795,Weather has been partly cloudy with occasional...

In [23]:
ubna_data_02_df = pd.read_csv('../output_dir/ubna_data_02_collected_audio_records.csv', index_col=0)
dc_season2 = ubna_data_02_df[pd.to_datetime(ubna_data_02_df['Datetime UTC'])<=dt.datetime(2022,10,18,0,0,0)]
dc_season2.head(5)

,Datetime UTC,Site name,Recover folder,AudioMoth #,SD card #,File path,File metadata,File status,Audiomoth temperature,Audiomoth battery,Sample rate,Audiomoth artist ID,File duration,Deployment notes
0,2022-08-26 00:45:21,Telephone Field,recover-20220828,A,7,/mnt/ubna_data_02/recover-20220828/UBNA_007/20...,Recorded at 00:45:21 26/08/2022 (UTC) by Audio...,Usable for detection,37.4C,4.3V,192000,AudioMoth 24F3190361CBE990,874.001270833333,Using 6 Panasonic AA Ni-MH batteries; Used Aco...
1,2022-08-26 01:00:00,Telephone Field,recover-20220828,A,7,/mnt/ubna_data_02/recover-20220828/UBNA_007/20...,Recorded at 01:00:00 26/08/2022 (UTC) by Audio...,Usable for detection,38.2C,4.3V,192000,AudioMoth 24F3190361CBE990,1795.00127083333,Using 6 Panasonic AA Ni-MH batteries; Used Aco...
2,2022-08-26 01:30:00,Telephone Field,recover-20220828,A,7,/mnt/ubna_data_02/recover-20220828/UBNA_007/20...,Recorded at 01:30:00 26/08/2022 (UTC) by Audio...,Usable for detection,37.5C,4.3V,192000,AudioMoth 24F3190361CBE990,1795.00127083333,Using 6 Panasonic AA Ni-MH batteries; Used Aco...
3,2022-08-26 02:00:00,Telephone Field,recover-20220828,A,7,/mnt/ubna_data_02/recover-20220828/UBNA_007/20...,Recorded at 02:00:00 26/08/2022 (UTC) by Audio...,Usable for detection,36.3C,4.2V,192000,AudioMoth 24F3190361CBE990,1795.00127083333,Using 6 Panasonic AA Ni-MH batteries; Used Aco...
4,2022-08-26 02:30:00,Telephone Field,recover-20220828,A,7,/mnt/ubna_data_02/recover-20220828/UBNA_007/20...,Recorded at 02:30:00 26/08/2022 (UTC) by Audio...,Usable for detection,34.4C,4.2V,192000,AudioMoth 24F3190361CBE990,1795.00127083333,Using 6 Panasonic AA Ni-MH batteries; Used Aco...

In [39]:
dc_season = pd.concat([dc_season1, dc_season2])
dc_season["Datetime UTC"] = pd.DatetimeIndex(dc_season["Datetime UTC"])
dc_season.set_index("Datetime UTC", inplace=True)
dc_season

,Site name,Recover folder,AudioMoth #,SD card #,File path,File metadata,File status,Audiomoth temperature,Audiomoth battery,Sample rate,Audiomoth artist ID,File duration,Deployment notes
Datetime UTC,,,,,,,,,,,,,
2022-06-14 22:36:27,Foliage,recover-20220616_unit2,C,010,/mnt/ubna_data_01/recover-20220616_unit2/20220...,Recorded at 22:36:27 14/06/2022 (UTC) by Audio...,Usable for detection,27.5C,4.7V,250000,AudioMoth 24F319055FDF2F5B,1408,Weather has been partly cloudy with occasional...
2022-06-14 23:00:00,Foliage,recover-20220616_unit2,C,010,/mnt/ubna_data_01/recover-20220616_unit2/20220...,Recorded at 23:00:00 14/06/2022 (UTC) by Audio...,Usable for detection,18.8C,4.7V,250000,AudioMoth 24F319055FDF2F5B,1795,Weather has been partly cloudy with occasional...
2022-06-14 23:30:00,Foliage,recover-20220616_unit2,C,010,/mnt/ubna_data_01/recover-20220616_unit2/20220...,Recorded at 23:30:00 14/06/2022 (UTC) by Audio...,Usable for detection,17.7C,4.6V,250000,AudioMoth 24F319055FDF2F5B,1795,Weather has been partly cloudy with occasional...
2022-06-15 00:00:00,Foliage,recover-20220616_unit2,C,010,/mnt/ubna_data_01/recover-20220616_unit2/20220...,Recorded at 00:00:00 15/06/2022 (UTC) by Audio...,Usable for detection,16.7C,4.6V,250000,AudioMoth 24F319055FDF2F5B,421,Weather has been partly cloudy with occasional...
2022-06-15 00:30:00,Foliage,recover-20220616_unit2,C,010,/mnt/ubna_data_01/recover-20220616_unit2/20220...,Recorded at 00:30:00 15/06/2022 (UTC) by Audio...,Usable for detection,16.0C,4.5V,250000,AudioMoth 24F319055FDF2F5B,1795,Weather has been partly cloudy with occasional...
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-17 22:00:00,Opposite Central Pond,recover-20221027,F,6,/mnt/ubna_data_02/recover-20221027/UBNA_006/20...,Recorded at 22:00:00 17/10/2022 (UTC) by Audio...,Usable for detection,23.3C,4.1V,192000,AudioMoth 249BC30461CBEB1A,300.001270833333,IKEA
2022-10-17 22:30:00,Opposite Central Pond,recover-20221027,F,6,/mnt/ubna_data_02/recover-20221027/UBNA_006/20...,Recorded at 22:30:00 17/10/2022 (UTC) by Audio...,Usable for detection,23.6C,4.1V,192000,AudioMoth 249BC30461CBEB1A,300.001270833333,IKEA
2022-10-17 23:00:00,Opposite Central Pond,recover-20221027,F,6,/mnt/ubna_data_02/recover-20221027/UBNA_006/20...,Recorded at 23:00:00 17/10/2022 (UTC) by Audio...,Usable for detection,23.1C,4.1V,192000,AudioMoth 249BC30461CBEB1A,300.001270833333,IKEA
2022-10-17 23:30:00,Opposite Central Pond,recover-20221027,F,6,/mnt/ubna_data_02/recover-20221027/UBNA_006/20...,Recorded at 23:30:00 17/10/2022 (UTC) by Audio...,Usable for detection,22.5C,4.1V,192000,AudioMoth 249BC30461CBEB1A,300.001270833333,IKEA
2022-10-18 00:00:00,Opposite Central Pond,recover-20221027,F,6,/mnt/ubna_data_02/recover-20221027/UBNA_006/20...,Recorded at 00:00:00 18/10/2022 (UTC) by Audio...,Usable for detection,22.0C,4.1V,192000,AudioMoth 249BC30461CBEB1A,300.001270833333,IKEA

In [111]:
def filter_df_with_location(ubna_data_df, cfg):
    site_name_cond = ubna_data_df["Site name"] == cfg['site']
    file_year_cond = ubna_data_df.index.year == (dt.datetime.strptime(cfg['year'], '%Y')).year
    minute_cond = np.logical_or((ubna_data_df.index).minute == 30, (ubna_data_df.index).minute == 0)
    datetime_cond = np.logical_and((ubna_data_df.index).second == 0, minute_cond)
    file_error_cond = np.logical_and((ubna_data_df["File duration"]!='File has no comment due to error!'), (ubna_data_df["File duration"]!='File has no Audiomoth-related comment'))
    all_errors_cond = np.logical_and((ubna_data_df["File duration"]!='Is empty!'), file_error_cond)

    filtered_location_df = ubna_data_df.loc[site_name_cond&datetime_cond&file_year_cond&all_errors_cond].sort_index()
    filtered_location_nightly_df = filtered_location_df.between_time(cfg['recording_start'], cfg['recording_end'], inclusive="left")

    return filtered_location_nightly_df

In [182]:
hour_recorded = dict()
hours_recorded_sum = 0
sites = ['Carp Pond', 'Telephone Field', 'Foliage', 'Central Pond', 'Fallen Tree', 'Opposite Central Pond']

In [183]:
site = sites[0]
cfg  = dict()
cfg["site"] = site
cfg["duration"] = 1795
cfg['year'] = '2022'
cfg['recording_start'] = '00:00'
cfg['recording_end'] = '16:00'

files_from_location = filter_df_with_location(dc_season, cfg)

ref_audio_files = sorted(list(files_from_location["File path"].apply(lambda x : Path(x)).values))
file_status_cond = files_from_location["File status"] == "Usable for detection"
file_duration_cond = np.isclose(files_from_location["File duration"].astype('float'), cfg['duration'])
good_location_df = files_from_location.loc[file_status_cond&file_duration_cond]
good_audio_files = sorted(list(good_location_df["File path"].apply(lambda x : Path(x)).values))
files_in_dc_study = good_location_df.loc[~good_location_df.index.duplicated(keep='last')]
seconds_recorded_in_dc_study = files_in_dc_study['File duration'].astype(np.float64)
minutes_recorded_in_dc_study = seconds_recorded_in_dc_study/60
hours_recorded_in_dc_study = minutes_recorded_in_dc_study/60
assert(len(sorted(list((Path.home() / f'duty-cycle-analysis/data/raw/{cfg["site"].split()[0]}').glob('bd2_*.csv')))) == good_location_df.loc[~good_location_df.index.duplicated(keep='last')].shape[0])
hour_recorded[cfg['site']] = hours_recorded_in_dc_study.sum()
hour_recorded[cfg['site']]

1420.5435681249983

In [184]:
site = sites[1]
cfg  = dict()
cfg["site"] = site
cfg["duration"] = 1795
cfg['year'] = '2022'
cfg['recording_start'] = '00:00'
cfg['recording_end'] = '16:00'

files_from_location = filter_df_with_location(dc_season, cfg)

ref_audio_files = sorted(list(files_from_location["File path"].apply(lambda x : Path(x)).values))
file_status_cond = files_from_location["File status"] == "Usable for detection"
file_duration_cond = np.isclose(files_from_location["File duration"].astype('float'), cfg['duration'])
good_location_df = files_from_location.loc[file_status_cond&file_duration_cond]
good_audio_files = sorted(list(good_location_df["File path"].apply(lambda x : Path(x)).values))
files_in_dc_study = good_location_df.loc[~good_location_df.index.duplicated(keep='last')]
seconds_recorded_in_dc_study = files_in_dc_study['File duration'].astype(np.float64)
minutes_recorded_in_dc_study = seconds_recorded_in_dc_study/60
hours_recorded_in_dc_study = minutes_recorded_in_dc_study/60
assert(len(sorted(list((Path.home() / f'duty-cycle-analysis/data/raw/{cfg["site"].split()[0]}').glob('bd2_*.csv')))) == good_location_df.loc[~good_location_df.index.duplicated(keep='last')].shape[0])
hour_recorded[cfg['site']] = hours_recorded_in_dc_study.sum()
hour_recorded[cfg['site']]

915.4504917418967

In [185]:
site = sites[2]
cfg  = dict()
cfg["site"] = site
cfg["duration"] = 1795
cfg['year'] = '2022'
cfg['recording_start'] = '00:00'
cfg['recording_end'] = '16:00'

files_from_location = filter_df_with_location(dc_season, cfg)

ref_audio_files = sorted(list(files_from_location["File path"].apply(lambda x : Path(x)).values))
file_status_cond = files_from_location["File status"] == "Usable for detection"
file_duration_cond = np.isclose(files_from_location["File duration"].astype('float'), cfg['duration'])
good_location_df = files_from_location.loc[file_status_cond&file_duration_cond]
good_audio_files = sorted(list(good_location_df["File path"].apply(lambda x : Path(x)).values))
files_in_dc_study = good_location_df.loc[~good_location_df.index.duplicated(keep='last')]
seconds_recorded_in_dc_study = files_in_dc_study['File duration'].astype(np.float64)
minutes_recorded_in_dc_study = seconds_recorded_in_dc_study/60
hours_recorded_in_dc_study = minutes_recorded_in_dc_study/60
hour_recorded[cfg['site']] = hours_recorded_in_dc_study.sum()
hour_recorded[cfg['site']]

1795.4991565104147

In [186]:
site = sites[3]
cfg  = dict()
cfg["site"] = site
cfg["duration"] = 1795
cfg['year'] = '2022'
cfg['recording_start'] = '00:00'
cfg['recording_end'] = '16:00'

files_from_location = filter_df_with_location(dc_season, cfg)

ref_audio_files = sorted(list(files_from_location["File path"].apply(lambda x : Path(x)).values))
file_status_cond = files_from_location["File status"] == "Usable for detection"
file_duration_cond = np.isclose(files_from_location["File duration"].astype('float'), cfg['duration'])
good_location_df = files_from_location.loc[file_status_cond&file_duration_cond]
good_audio_files = sorted(list(good_location_df["File path"].apply(lambda x : Path(x)).values))
files_in_dc_study = good_location_df.loc[~good_location_df.index.duplicated(keep='last')]
seconds_recorded_in_dc_study = files_in_dc_study['File duration'].astype(np.float64)
minutes_recorded_in_dc_study = seconds_recorded_in_dc_study/60
hours_recorded_in_dc_study = minutes_recorded_in_dc_study/60
hour_recorded[cfg['site']] = hours_recorded_in_dc_study.sum()
hour_recorded[cfg['site']]

1321.8185991898133

In [187]:
site = sites[4]
cfg  = dict()
cfg["site"] = site
cfg["duration"] = 1795
cfg['year'] = '2022'
cfg['recording_start'] = '00:00'
cfg['recording_end'] = '16:00'

files_from_location = filter_df_with_location(dc_season, cfg)

ref_audio_files = sorted(list(files_from_location["File path"].apply(lambda x : Path(x)).values))
file_status_cond = files_from_location["File status"] == "Usable for detection"
file_duration_cond = np.isclose(files_from_location["File duration"].astype('float'), cfg['duration'])
good_location_df = files_from_location.loc[file_status_cond&file_duration_cond]
good_audio_files = sorted(list(good_location_df["File path"].apply(lambda x : Path(x)).values))
files_in_dc_study = good_location_df.loc[~good_location_df.index.duplicated(keep='last')]
seconds_recorded_in_dc_study = files_in_dc_study['File duration'].astype(np.float64)
minutes_recorded_in_dc_study = seconds_recorded_in_dc_study/60
hours_recorded_in_dc_study = minutes_recorded_in_dc_study/60
hour_recorded[cfg['site']] = hours_recorded_in_dc_study.sum()
hour_recorded[cfg['site']]

866.5866035590263

In [188]:
site = sites[5]
cfg  = dict()
cfg["site"] = site
cfg["duration"] = 1795
cfg['year'] = '2022'
cfg['recording_start'] = '00:00'
cfg['recording_end'] = '16:00'

files_from_location = filter_df_with_location(dc_season, cfg)

ref_audio_files = sorted(list(files_from_location["File path"].apply(lambda x : Path(x)).values))
file_status_cond = files_from_location["File status"] == "Usable for detection"
file_duration_cond = np.isclose(files_from_location["File duration"].astype('float'), cfg['duration'])
good_location_df = files_from_location.loc[file_status_cond&file_duration_cond]
good_audio_files = sorted(list(good_location_df["File path"].apply(lambda x : Path(x)).values))
files_in_dc_study = good_location_df.loc[~good_location_df.index.duplicated(keep='last')]
seconds_recorded_in_dc_study = files_in_dc_study['File duration'].astype(np.float64)
minutes_recorded_in_dc_study = seconds_recorded_in_dc_study/60
hours_recorded_in_dc_study = minutes_recorded_in_dc_study/60
hour_recorded[cfg['site']] = hours_recorded_in_dc_study.sum()
hour_recorded[cfg['site']]

733.4574294791653

In [189]:
hour_recorded

{'Carp Pond': 1420.5435681249983,
 'Telephone Field': 915.4504917418967,
 'Foliage': 1795.4991565104147,
 'Central Pond': 1321.8185991898133,
 'Fallen Tree': 866.5866035590263,
 'Opposite Central Pond': 733.4574294791653}

In [190]:
for site in sites:
    print(hour_recorded[site])
    hours_recorded_sum += hour_recorded[site]
print(f'{hours_recorded_sum:.2f} hours of data fed into detection from Carp Pond and Telephone Field')

1420.5435681249983
915.4504917418967
1795.4991565104147
1321.8185991898133
866.5866035590263
733.4574294791653
7053.36 hours of data fed into detection from Carp Pond and Telephone Field

In [192]:
hour_recorded = dict()
hours_recorded_sum = 0
sites = ['Carp Pond', 'Telephone Field', 'Foliage', 'Central Pond']
for site in sites:
    cfg  = dict()
    cfg["site"] = site
    cfg["duration"] = 1795
    cfg['year'] = '2022'
    cfg['recording_start'] = '00:00'
    cfg['recording_end'] = '16:00'

    files_from_location = filter_df_with_location(dc_season, cfg)

    ref_audio_files = sorted(list(files_from_location["File path"].apply(lambda x : Path(x)).values))
    file_status_cond = files_from_location["File status"] == "Usable for detection"
    file_duration_cond = np.isclose(files_from_location["File duration"].astype('float'), cfg['duration'])
    good_location_df = files_from_location.loc[file_status_cond&file_duration_cond]
    good_audio_files = sorted(list(good_location_df["File path"].apply(lambda x : Path(x)).values))
    files_in_dc_study = good_location_df.loc[~good_location_df.index.duplicated(keep='last')]
    seconds_recorded_in_dc_study = files_in_dc_study['File duration'].astype(np.float64)
    minutes_recorded_in_dc_study = seconds_recorded_in_dc_study/60
    hours_recorded_in_dc_study = minutes_recorded_in_dc_study/60
    hour_recorded[cfg['site']] = hours_recorded_in_dc_study.sum()
    hours_recorded_sum += hour_recorded[cfg['site']]
print(f'{hours_recorded_sum:.2f} hours of data fed into detection from Carp Pond and Telephone Field')

5453.31 hours of data fed into detection from Carp Pond and Telephone Field